services:
  db:
    image: postgres:16-alpine
    container_name: subscriptions-db
    environment:
      POSTGRES_USER: subscriptions_user
      POSTGRES_PASSWORD: subscriptions_pass
      POSTGRES_DB: subscriptions_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U subscriptions_user"]
      interval: 2s
      timeout: 2s
      retries: 10

  app:
    build: .
    container_name: subscriptions-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_DRIVER: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: subscriptions_user
      DB_PASSWORD: subscriptions_pass
      DB_NAME: subscriptions_db
      DB_SSLMODE: disable
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      LOG_LEVEL: info
    ports:
      - "8080:8080"
    command: ["./subscriptions-api", "-serve"]

volumes:
  db_data: 